#!/usr/bin/env bash

usage() {
    echo "Usage: emacsd [start|stop|restart]"
}

start() {
    emacs --daemon
}

stop() {
    emacsclient -e "(kill-emacs)"
}

restart() {
    stop
    start
}

if [ $# -eq 1 ]; then
    if [ "$1" = "start" ]; then
        start
    elif [ "$1" = "stop" ]; then
        stop
    elif [ "$1" = "restart" ]; then
        restart
    else
        usage
    fi
# If no CLA's provided, offer a menu
elif [ $# -eq 0 ]; then
    OPTIONS="start stop restart nevermind"
    select opt in $OPTIONS; do
        if [ "$opt" = "start" ]; then
            start
            exit
        elif [ "$opt" = "stop" ]; then
            stop
            exit
        elif [ "$opt" = "restart" ]; then
            restart
            exit
	    elif [ "$opt" = "nevermind" ]; then
	    exit
        else
            echo Usage: emacsd [start|stop|restart]
        fi
    done
else
    usage
fi
